<?php

const PAYJOE_STATUS_PENDING = 10;
const PAYJOE_STATUS_OK      = 20;
const PAYJOE_STATUS_ERROR   = 30;
const PAYJOE_STATUS_RESEND  = 9989;

const PAYJOE_PLUGIN_TYPE_WCPDF         = 0;
const PAYJOE_PLUGIN_TYPE_GERMANIZED    = 1;
const PAYJOE_PLUGIN_TYPE_GERMAN_MARKET = 2;
